import machine.Alphabet

val rotor1Substitution = mapOf(
    Alphabet.A to Alphabet.F,
    Alphabet.B to Alphabet.W,
    Alphabet.C to Alphabet.N,
    Alphabet.D to Alphabet.C,
    Alphabet.E to Alphabet.TROIS,
    Alphabet.F to Alphabet.ZERO,
    Alphabet.G to Alphabet.A,
    Alphabet.H to Alphabet.P,
    Alphabet.I to Alphabet.T,
    Alphabet.J to Alphabet.DEUX,
    Alphabet.K to Alphabet.X,
    Alphabet.L to Alphabet.CINQ,
    Alphabet.M to Alphabet.L,
    Alphabet.N to Alphabet.E,
    Alphabet.O to Alphabet.R,
    Alphabet.P to Alphabet.V,
    Alphabet.Q to Alphabet.M,
    Alphabet.R to Alphabet.NEUF,
    Alphabet.S to Alphabet.S,
    Alphabet.T to Alphabet.Q,
    Alphabet.U to Alphabet.B,
    Alphabet.V to Alphabet.U,
    Alphabet.W to Alphabet.HUIT,
    Alphabet.X to Alphabet.G,
    Alphabet.Y to Alphabet.Y,
    Alphabet.Z to Alphabet.SPACE,
    Alphabet.ZERO to Alphabet.UN,
    Alphabet.UN to Alphabet.SEPT,
    Alphabet.DEUX to Alphabet.QUATRE,
    Alphabet.TROIS to Alphabet.K,
    Alphabet.QUATRE to Alphabet.H,
    Alphabet.CINQ to Alphabet.O,
    Alphabet.SIX to Alphabet.I,
    Alphabet.SEPT to Alphabet.J,
    Alphabet.HUIT to Alphabet.SIX,
    Alphabet.NEUF to Alphabet.Z,
    Alphabet.POINT to Alphabet.D,
    Alphabet.SPACE to Alphabet.POINT
)

val rotor2Substitution = mapOf(
    Alphabet.A to Alphabet.HUIT,
    Alphabet.B to Alphabet.Z,
    Alphabet.C to Alphabet.U,
    Alphabet.D to Alphabet.CINQ,
    Alphabet.E to Alphabet.SPACE,
    Alphabet.F to Alphabet.NEUF,
    Alphabet.G to Alphabet.P,
    Alphabet.H to Alphabet.V,
    Alphabet.I to Alphabet.C,
    Alphabet.J to Alphabet.W,
    Alphabet.K to Alphabet.R,
    Alphabet.L to Alphabet.TROIS,
    Alphabet.M to Alphabet.ZERO,
    Alphabet.N to Alphabet.DEUX,
    Alphabet.O to Alphabet.Q,
    Alphabet.P to Alphabet.N,
    Alphabet.Q to Alphabet.F,
    Alphabet.R to Alphabet.X,
    Alphabet.S to Alphabet.UN,
    Alphabet.T to Alphabet.S,
    Alphabet.U to Alphabet.E,
    Alphabet.V to Alphabet.L,
    Alphabet.W to Alphabet.D,
    Alphabet.X to Alphabet.A,
    Alphabet.Y to Alphabet.M,
    Alphabet.Z to Alphabet.O,
    Alphabet.ZERO to Alphabet.B,
    Alphabet.UN to Alphabet.I,
    Alphabet.DEUX to Alphabet.J,
    Alphabet.TROIS to Alphabet.POINT,
    Alphabet.QUATRE to Alphabet.K,
    Alphabet.CINQ to Alphabet.SEPT,
    Alphabet.SIX to Alphabet.QUATRE,
    Alphabet.SEPT to Alphabet.T,
    Alphabet.HUIT to Alphabet.SIX,
    Alphabet.NEUF to Alphabet.Y,
    Alphabet.POINT to Alphabet.G,
    Alphabet.SPACE to Alphabet.H
)

val rotor3Substitution = mapOf(
    Alphabet.A to Alphabet.J,
    Alphabet.B to Alphabet.L,
    Alphabet.C to Alphabet.Z,
    Alphabet.D to Alphabet.UN,
    Alphabet.E to Alphabet.SEPT,
    Alphabet.F to Alphabet.U,
    Alphabet.G to Alphabet.NEUF,
    Alphabet.H to Alphabet.V,
    Alphabet.I to Alphabet.F,
    Alphabet.J to Alphabet.R,
    Alphabet.K to Alphabet.HUIT,
    Alphabet.L to Alphabet.H,
    Alphabet.M to Alphabet.POINT,
    Alphabet.N to Alphabet.TROIS,
    Alphabet.O to Alphabet.QUATRE,
    Alphabet.P to Alphabet.I,
    Alphabet.Q to Alphabet.C,
    Alphabet.R to Alphabet.SIX,
    Alphabet.S to Alphabet.Q,
    Alphabet.T to Alphabet.N,
    Alphabet.U to Alphabet.CINQ,
    Alphabet.V to Alphabet.T,
    Alphabet.W to Alphabet.ZERO,
    Alphabet.X to Alphabet.M,
    Alphabet.Y to Alphabet.O,
    Alphabet.Z to Alphabet.DEUX,
    Alphabet.ZERO to Alphabet.X,
    Alphabet.UN to Alphabet.P,
    Alphabet.DEUX to Alphabet.Y,
    Alphabet.TROIS to Alphabet.SPACE,
    Alphabet.QUATRE to Alphabet.D,
    Alphabet.CINQ to Alphabet.W,
    Alphabet.SIX to Alphabet.S,
    Alphabet.SEPT to Alphabet.B,
    Alphabet.HUIT to Alphabet.K,
    Alphabet.NEUF to Alphabet.G,
    Alphabet.POINT to Alphabet.A,
    Alphabet.SPACE to Alphabet.E
)

val rotor1Sub = listOf(
    Alphabet.F,
    Alphabet.W,
    Alphabet.N,
    Alphabet.C,
    Alphabet.TROIS,
    Alphabet.ZERO,
    Alphabet.A,
    Alphabet.P,
    Alphabet.T,
    Alphabet.DEUX,
    Alphabet.X,
    Alphabet.CINQ,
    Alphabet.L,
    Alphabet.E,
    Alphabet.R,
    Alphabet.V,
    Alphabet.M,
    Alphabet.NEUF,
    Alphabet.S,
    Alphabet.Q,
    Alphabet.B,
    Alphabet.U,
    Alphabet.HUIT,
    Alphabet.G,
    Alphabet.Y,
    Alphabet.SPACE,
    Alphabet.UN,
    Alphabet.SEPT,
    Alphabet.QUATRE,
    Alphabet.K,
    Alphabet.H,
    Alphabet.O,
    Alphabet.I,
    Alphabet.J,
    Alphabet.SIX,
    Alphabet.Z,
    Alphabet.D,
    Alphabet.POINT
)

val rotor2Sub = listOf(
    Alphabet.HUIT,
    Alphabet.Z,
    Alphabet.U,
    Alphabet.CINQ,
    Alphabet.SPACE,
    Alphabet.NEUF,
    Alphabet.P,
    Alphabet.V,
    Alphabet.C,
    Alphabet.W,
    Alphabet.R,
    Alphabet.TROIS,
    Alphabet.ZERO,
    Alphabet.DEUX,
    Alphabet.Q,
    Alphabet.N,
    Alphabet.F,
    Alphabet.X,
    Alphabet.UN,
    Alphabet.S,
    Alphabet.E,
    Alphabet.L,
    Alphabet.D,
    Alphabet.A,
    Alphabet.M,
    Alphabet.O,
    Alphabet.B,
    Alphabet.I,
    Alphabet.J,
    Alphabet.POINT,
    Alphabet.K,
    Alphabet.SEPT,
    Alphabet.QUATRE,
    Alphabet.T,
    Alphabet.SIX,
    Alphabet.Y,
    Alphabet.G,
    Alphabet.H
)

val rotor3Sub = listOf(
    Alphabet.J,
    Alphabet.L,
    Alphabet.Z,
    Alphabet.UN,
    Alphabet.SEPT,
    Alphabet.U,
    Alphabet.NEUF,
    Alphabet.V,
    Alphabet.F,
    Alphabet.R,
    Alphabet.HUIT,
    Alphabet.H,
    Alphabet.POINT,
    Alphabet.TROIS,
    Alphabet.QUATRE,
    Alphabet.I,
    Alphabet.C,
    Alphabet.SIX,
    Alphabet.Q,
    Alphabet.N,
    Alphabet.CINQ,
    Alphabet.T,
    Alphabet.ZERO,
    Alphabet.M,
    Alphabet.O,
    Alphabet.DEUX,
    Alphabet.X,
    Alphabet.P,
    Alphabet.Y,
    Alphabet.SPACE,
    Alphabet.D,
    Alphabet.W,
    Alphabet.S,
    Alphabet.B,
    Alphabet.K,
    Alphabet.G,
    Alphabet.A,
    Alphabet.E,
)